# -*- coding: utf-8 -*-
"""Per-archetype defaults: clearances (mm), placement flags, layout hints.
Emitted verbatim to archetypes.json. SPEC v1 §4.3 closed set.
"""

# c = clearance front/back/left/right ; p = placement overrides ; hints = layout engine hints
A = {
 # ---------------------------------------------------------------- seating
 "sofa_3seat":       {"c":(750,50,100,100), "p":{"against_wall":True,"wall_offset_mm":40,"center_ok":False},
                      "hints":{"zone":"seating","anchor":True,"faces":"focal","pairs_with":["coffee_table","rug","armchair"],"min_room_area_m2":11.0}},
 "sofa_2seat":       {"c":(750,50,100,100), "p":{"against_wall":True,"wall_offset_mm":40,"center_ok":False},
                      "hints":{"zone":"seating","anchor":True,"faces":"focal","pairs_with":["coffee_table","rug"],"min_room_area_m2":8.0}},
 "loveseat":         {"c":(700,50,100,100), "p":{"against_wall":True,"wall_offset_mm":40,"corner_ok":True,"center_ok":False},
                      "hints":{"zone":"seating","anchor":True,"faces":"focal","pairs_with":["coffee_table","rug"],"min_room_area_m2":7.0}},
 "sofa_sectional_l": {"c":(750,50,80,80),   "p":{"against_wall":True,"wall_offset_mm":40,"corner_ok":True,"center_ok":False},
                      "hints":{"zone":"seating","anchor":True,"faces":"focal","pairs_with":["coffee_table","rug"],"min_room_area_m2":15.0}},
 "chaise":           {"c":(600,50,80,80),   "p":{"against_wall":True,"wall_offset_mm":40,"corner_ok":True,"center_ok":False},
                      "hints":{"zone":"seating","anchor":False,"faces":"focal","pairs_with":["sofa_3seat"],"min_room_area_m2":10.0}},
 "armchair":         {"c":(600,50,150,150), "p":{"against_wall":False,"wall_offset_mm":60,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"seating","anchor":False,"faces":"focal","pairs_with":["floor_lamp","side_table"],"min_room_area_m2":4.0}},
 "ottoman":          {"c":(300,300,300,300),"p":{"against_wall":False,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"seating","anchor":False,"faces":"free","pairs_with":["armchair","sofa_3seat"],"min_room_area_m2":2.0}},
 "bench":            {"c":(600,50,100,100), "p":{"against_wall":True,"wall_offset_mm":30,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"circulation","anchor":False,"faces":"wall","pairs_with":["dining_table_rect"],"min_room_area_m2":3.0}},
 "dining_chair":     {"c":(300,1100,150,150),"p":{"against_wall":False,"corner_ok":True,"center_ok":True,"stackable":True},
                      "hints":{"zone":"dining","anchor":False,"faces":"table","pairs_with":["dining_table_rect","dining_table_round"],"min_room_area_m2":1.0}},
 "office_chair":     {"c":(300,900,300,300),"p":{"against_wall":False,"corner_ok":False,"center_ok":True},
                      "hints":{"zone":"work","anchor":False,"faces":"desk","pairs_with":["desk"],"min_room_area_m2":2.0}},
 "stool":            {"c":(300,300,250,250),"p":{"against_wall":False,"corner_ok":True,"center_ok":True,"stackable":True},
                      "hints":{"zone":"flex","anchor":False,"faces":"free","pairs_with":["kitchen_island"],"min_room_area_m2":1.0}},
 "bar_stool":        {"c":(300,900,200,200),"p":{"against_wall":False,"corner_ok":False,"center_ok":True},
                      "hints":{"zone":"kitchen","anchor":False,"faces":"counter","pairs_with":["kitchen_island"],"min_room_area_m2":1.5}},
 # ---------------------------------------------------------------- beds
 "bed_single":       {"c":(700,0,600,300),  "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":True,"center_ok":False},
                      "hints":{"zone":"sleep","anchor":True,"faces":"room","pairs_with":["nightstand"],"min_room_area_m2":6.0}},
 "bed_double":       {"c":(700,0,700,700),  "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":False,"center_ok":False},
                      "hints":{"zone":"sleep","anchor":True,"faces":"room","pairs_with":["nightstand","dresser"],"min_room_area_m2":9.0}},
 "bed_queen":        {"c":(750,0,700,700),  "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":False,"center_ok":False},
                      "hints":{"zone":"sleep","anchor":True,"faces":"room","pairs_with":["nightstand","dresser"],"min_room_area_m2":11.0}},
 "bed_king":         {"c":(750,0,750,750),  "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":False,"center_ok":False},
                      "hints":{"zone":"sleep","anchor":True,"faces":"room","pairs_with":["nightstand","dresser"],"min_room_area_m2":14.0}},
 "crib":             {"c":(600,0,300,300),  "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":True,"center_ok":False},
                      "hints":{"zone":"sleep","anchor":True,"faces":"room","pairs_with":["dresser"],"min_room_area_m2":6.0}},
 # ---------------------------------------------------------------- storage
 "nightstand":       {"c":(450,20,50,50),   "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":True,"center_ok":False},
                      "hints":{"zone":"sleep","anchor":False,"faces":"room","pairs_with":["bed_queen","table_lamp"],"min_room_area_m2":0.5}},
 "dresser":          {"c":(900,20,50,50),   "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":False,"center_ok":False},
                      "hints":{"zone":"sleep","anchor":False,"faces":"room","pairs_with":["mirror"],"min_room_area_m2":3.0}},
 "wardrobe":         {"c":(900,20,20,20),   "p":{"against_wall":True,"wall_offset_mm":10,"corner_ok":True,"center_ok":False},
                      "hints":{"zone":"sleep","anchor":False,"faces":"room","pairs_with":[],"min_room_area_m2":6.0}},
 "bookcase":         {"c":(800,20,20,20),   "p":{"against_wall":True,"wall_offset_mm":15,"corner_ok":True,"center_ok":False},
                      "hints":{"zone":"storage","anchor":False,"faces":"room","pairs_with":["armchair","floor_lamp"],"min_room_area_m2":3.0}},
 "shelf_unit":       {"c":(800,20,20,20),   "p":{"against_wall":True,"wall_offset_mm":15,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"storage","anchor":False,"faces":"room","pairs_with":["storage_box"],"min_room_area_m2":3.0}},
 "sideboard":        {"c":(900,20,50,50),   "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":False,"center_ok":False},
                      "hints":{"zone":"storage","anchor":False,"faces":"room","pairs_with":["art_frame","mirror"],"min_room_area_m2":4.0}},
 "cabinet":          {"c":(800,20,50,50),   "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":True,"center_ok":False},
                      "hints":{"zone":"storage","anchor":False,"faces":"room","pairs_with":[],"min_room_area_m2":2.0}},
 "tv_bench":         {"c":(1000,20,50,50),  "p":{"against_wall":True,"wall_offset_mm":30,"corner_ok":False,"center_ok":False},
                      "hints":{"zone":"seating","anchor":False,"faces":"sofa","pairs_with":["tv","sofa_3seat"],"min_room_area_m2":8.0}},
 "storage_box":      {"c":(300,0,0,0),      "p":{"against_wall":True,"wall_offset_mm":0,"corner_ok":True,"center_ok":True,"stackable":True},
                      "hints":{"zone":"storage","anchor":False,"faces":"free","pairs_with":["shelf_unit"],"min_room_area_m2":0.2}},
 # ---------------------------------------------------------------- tables
 "coffee_table":     {"c":(400,400,400,400),"p":{"against_wall":False,"corner_ok":False,"center_ok":True},
                      "hints":{"zone":"seating","anchor":False,"faces":"free","pairs_with":["sofa_3seat","rug"],"min_room_area_m2":8.0,
                               "offset_from_mm":{"sofa_3seat":400,"sofa_2seat":400,"loveseat":380,"sofa_sectional_l":420}}},
 "side_table":       {"c":(300,150,150,150),"p":{"against_wall":False,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"seating","anchor":False,"faces":"free","pairs_with":["armchair","sofa_3seat"],"min_room_area_m2":2.0}},
 "dining_table_rect":{"c":(1100,1100,1100,1100),"p":{"against_wall":False,"corner_ok":False,"center_ok":True},
                      "hints":{"zone":"dining","anchor":True,"faces":"free","pairs_with":["dining_chair","pendant_lamp"],"min_room_area_m2":9.0,
                               "seat_pitch_mm":600}},
 "dining_table_round":{"c":(1100,1100,1100,1100),"p":{"against_wall":False,"corner_ok":False,"center_ok":True},
                      "hints":{"zone":"dining","anchor":True,"faces":"free","pairs_with":["dining_chair","pendant_lamp"],"min_room_area_m2":8.0,
                               "seat_pitch_mm":600}},
 "desk":             {"c":(900,20,100,100), "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"work","anchor":True,"faces":"room","pairs_with":["office_chair","table_lamp"],"min_room_area_m2":4.0}},
 "console_table":    {"c":(600,20,50,50),   "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":True,"center_ok":False},
                      "hints":{"zone":"circulation","anchor":False,"faces":"room","pairs_with":["mirror","table_lamp"],"min_room_area_m2":2.0}},
 "kitchen_island":   {"c":(1000,1000,1000,1000),"p":{"against_wall":False,"corner_ok":False,"center_ok":True},
                      "hints":{"zone":"kitchen","anchor":True,"faces":"free","pairs_with":["bar_stool","pendant_lamp"],"min_room_area_m2":12.0}},
 # ---------------------------------------------------------------- soft / light
 "rug":              {"c":(0,0,0,0),        "p":{"against_wall":False,"wall_offset_mm":0,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"seating","anchor":False,"faces":"free","pairs_with":["sofa_3seat"],"min_room_area_m2":6.0,
                               "no_collider":True,"under_group_overlap_mm":200}},
 "floor_lamp":       {"c":(150,80,150,150), "p":{"against_wall":False,"wall_offset_mm":60,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"seating","anchor":False,"faces":"free","pairs_with":["armchair","sofa_3seat"],"min_room_area_m2":1.0}},
 "table_lamp":       {"c":(50,20,50,50),    "p":{"against_wall":False,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"any","anchor":False,"faces":"free","pairs_with":["nightstand","sideboard"],"min_room_area_m2":0.2,
                               "sits_on_surface":True}},
 "pendant_lamp":     {"c":(0,0,0,0),        "p":{"against_wall":False,"corner_ok":False,"center_ok":True,"ceiling_mounted":True},
                      "hints":{"zone":"any","anchor":False,"faces":"free","pairs_with":["dining_table_rect","kitchen_island"],"min_room_area_m2":4.0,
                               "no_collider":True,"drop_below_ceiling_mm":1200,"centre_over":["dining_table_rect","dining_table_round","kitchen_island"]}},
 "wall_lamp":        {"c":(0,0,0,0),        "p":{"against_wall":True,"wall_offset_mm":0,"corner_ok":True,"center_ok":False,
                                                 "wall_mounted":True,"mount_h_mm":1500},
                      "hints":{"zone":"any","anchor":False,"faces":"room","pairs_with":["bed_queen"],"min_room_area_m2":1.0,"no_collider":True}},
 # ---------------------------------------------------------------- decor
 "tv":               {"c":(1600,0,100,100), "p":{"against_wall":True,"wall_offset_mm":40,"corner_ok":False,"center_ok":False,
                                                 "wall_mounted":True,"mount_h_mm":1000},
                      "hints":{"zone":"seating","anchor":False,"faces":"sofa","pairs_with":["tv_bench","sofa_3seat"],"min_room_area_m2":8.0,
                               "no_collider":True,"view_dist_mult":[1.6,2.5],"centre_h_mm":[1000,1150]}},
 "art_frame":        {"c":(0,0,0,0),        "p":{"against_wall":True,"wall_offset_mm":0,"corner_ok":False,"center_ok":False,
                                                 "wall_mounted":True,"mount_h_mm":1500},
                      "hints":{"zone":"any","anchor":False,"faces":"room","pairs_with":["sideboard","sofa_3seat"],"min_room_area_m2":0.0,"no_collider":True}},
 "mirror":           {"c":(0,0,0,0),        "p":{"against_wall":True,"wall_offset_mm":0,"corner_ok":False,"center_ok":False,
                                                 "wall_mounted":True,"mount_h_mm":1400},
                      "hints":{"zone":"any","anchor":False,"faces":"room","pairs_with":["console_table","dresser"],"min_room_area_m2":0.0,"no_collider":True}},
 "plant":            {"c":(100,80,100,100), "p":{"against_wall":False,"wall_offset_mm":50,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"any","anchor":False,"faces":"free","pairs_with":[],"min_room_area_m2":0.5}},
 "curtain":          {"c":(0,0,0,0),        "p":{"against_wall":True,"wall_offset_mm":0,"corner_ok":False,"center_ok":False,
                                                 "wall_mounted":True,"mount_h_mm":2400},
                      "hints":{"zone":"any","anchor":False,"faces":"room","pairs_with":[],"min_room_area_m2":0.0,
                               "no_collider":True,"aligns_to":"window","wall_len_margin_mm":200}},
 "wall_shelf":       {"c":(400,0,0,0),      "p":{"against_wall":True,"wall_offset_mm":0,"corner_ok":True,"center_ok":False,
                                                 "wall_mounted":True,"mount_h_mm":1400},
                      "hints":{"zone":"storage","anchor":False,"faces":"room","pairs_with":["art_frame"],"min_room_area_m2":0.0,"no_collider":True}},
 # ---------------------------------------------------------------- SPEC2 I2 additions (generic defaults)
 "monitor":          {"c":(80,50,50,50),   "p":{"against_wall":False,"wall_offset_mm":30,"corner_ok":False,"center_ok":True},
                      "hints":{"zone":"work","anchor":False,"faces":"chair","pairs_with":["desk","office_chair"],"min_room_area_m2":1.0}},
 "appliance":        {"c":(300,50,50,50),  "p":{"against_wall":True,"wall_offset_mm":30,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"utility","anchor":False,"faces":"room","pairs_with":["kitchen_island","desk"],"min_room_area_m2":1.0}},
 "rack":             {"c":(500,20,50,50),  "p":{"against_wall":True,"wall_offset_mm":20,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"utility","anchor":False,"faces":"room","pairs_with":["wardrobe"],"min_room_area_m2":1.5}},
 "cushion":          {"c":(200,200,200,200),"p":{"against_wall":False,"wall_offset_mm":0,"corner_ok":True,"center_ok":True},
                      "hints":{"zone":"seating","anchor":False,"faces":"free","pairs_with":["rug","coffee_table"],"min_room_area_m2":2.0}},
 "bike":             {"c":(600,20,100,100),"p":{"against_wall":True,"wall_offset_mm":30,"corner_ok":True,"center_ok":False},
                      "hints":{"zone":"circulation","anchor":False,"faces":"wall","pairs_with":[],"min_room_area_m2":3.0}},
 "curtain_rod":      {"c":(0,0,0,0),       "p":{"against_wall":True,"wall_offset_mm":0,"corner_ok":False,"center_ok":False,"wall_mounted":True,"mount_h_mm":2250},
                      "hints":{"zone":"window","anchor":False,"faces":"room","pairs_with":["curtain"],"min_room_area_m2":0.0}},
 "string_lights":    {"c":(0,0,0,0),       "p":{"against_wall":False,"wall_offset_mm":0,"corner_ok":True,"center_ok":True,"ceiling_mounted":True},
                      "hints":{"zone":"ambient","anchor":False,"faces":"free","pairs_with":[],"min_room_area_m2":0.0}},
}


CATEGORIES = ["seating","tables","beds","storage","desks","lighting","rugs","decor","appliance","outdoor","kids"]

SANITY = {
 "sofa_2seat":       {"w":[1300,2050],"d":[750,1100],"h":[600,1100],"seat_h":[380,500]},
 "sofa_3seat":       {"w":[1900,2600],"d":[800,1150],"h":[600,1150],"seat_h":[380,500]},
 "sofa_sectional_l": {"w":[2000,3400],"d":[1300,2000],"h":[600,1150],"seat_h":[380,500]},
 "loveseat":         {"w":[1200,1900],"d":[750,1050],"h":[600,1050],"seat_h":[380,500]},
 "chaise":           {"w":[800,2000],"d":[900,1900],"h":[600,1100],"seat_h":[380,500]},
 "armchair":         {"w":[600,1150],"d":[650,1050],"h":[650,1100],"seat_h":[380,500]},
 "ottoman":          {"w":[380,900],"d":[380,750],"h":[300,520],"seat_h":[300,520]},
 "bench":            {"w":[700,1800],"d":[300,600],"h":[400,560],"seat_h":[400,560]},
 "dining_chair":     {"w":[280,600],"d":[300,600],"h":[500,1000],"seat_h":[280,500]},
 "office_chair":     {"w":[550,750],"d":[550,750],"h":[800,1450],"seat_h":[400,520]},
 "stool":            {"w":[280,500],"d":[280,500],"h":[400,600],"seat_h":[400,600]},
 "bar_stool":        {"w":[320,550],"d":[350,600],"h":[600,1100],"seat_h":[600,820]},
 "bed_single":       {"w":[800,1000],"d":[1850,2200],"h":[250,1250],"seat_h":[250,520]},
 "bed_double":       {"w":[1300,1450],"d":[1900,2250],"h":[250,1450],"seat_h":[250,520]},
 "bed_queen":        {"w":[1500,1720],"d":[1950,2250],"h":[250,1450],"seat_h":[250,520]},
 "bed_king":         {"w":[1850,2050],"d":[1950,2300],"h":[250,1450],"seat_h":[250,520]},
 "crib":             {"w":[600,800],"d":[1150,1350],"h":[700,1100],"seat_h":None},
 "nightstand":       {"w":[280,600],"d":[250,550],"h":[400,800],"seat_h":None},
 "dresser":          {"w":[600,1400],"d":[350,600],"h":[600,1450],"seat_h":None},
 "wardrobe":         {"w":[700,2600],"d":[400,700],"h":[1150,2500],"seat_h":None},
 "bookcase":         {"w":[350,1100],"d":[200,420],"h":[700,2200],"seat_h":None},
 "shelf_unit":       {"w":[380,2000],"d":[250,500],"h":[600,2000],"seat_h":None},
 "sideboard":        {"w":[900,2100],"d":[350,600],"h":[600,1100],"seat_h":None},
 "cabinet":          {"w":[300,1200],"d":[250,600],"h":[500,1500],"seat_h":None},
 "tv_bench":         {"w":[700,2400],"d":[200,600],"h":[300,700],"seat_h":None},
 "storage_box":      {"w":[150,800],"d":[150,800],"h":[80,700],"seat_h":None},
 "coffee_table":     {"w":[500,1900],"d":[400,1000],"h":[350,500],"seat_h":None},
 "side_table":       {"w":[300,700],"d":[300,700],"h":[400,750],"seat_h":None},
 "dining_table_rect":{"w":[700,2600],"d":[450,1100],"h":[500,780],"seat_h":None},
 "dining_table_round":{"w":[800,1500],"d":[800,1500],"h":[680,780],"seat_h":None},
 "desk":             {"w":[900,1900],"d":[350,900],"h":[700,820],"seat_h":None},
 "console_table":    {"w":[700,1600],"d":[250,500],"h":[700,900],"seat_h":None},
 "kitchen_island":   {"w":[900,2200],"d":[600,1100],"h":[850,960],"seat_h":None},
 "rug":              {"w":[450,4000],"d":[400,5000],"h":[4,60],"seat_h":None},
 "floor_lamp":       {"w":[150,700],"d":[150,700],"h":[1100,2000],"seat_h":None},
 "table_lamp":       {"w":[120,400],"d":[120,400],"h":[150,700],"seat_h":None},
 "pendant_lamp":     {"w":[150,900],"d":[150,900],"h":[300,2000],"seat_h":None},
 "wall_lamp":        {"w":[80,400],"d":[100,400],"h":[100,600],"seat_h":None},
 "tv":               {"w":[700,2000],"d":[30,300],"h":[400,1200],"seat_h":None},
 "art_frame":        {"w":[150,2000],"d":[15,120],"h":[150,2000],"seat_h":None},
 "mirror":           {"w":[250,1400],"d":[15,150],"h":[250,2200],"seat_h":None},
 "plant":            {"w":[120,900],"d":[120,900],"h":[150,2200],"seat_h":None},
 "curtain":          {"w":[600,3000],"d":[40,250],"h":[1200,3200],"seat_h":None},
 "wall_shelf":       {"w":[300,2000],"d":[80,400],"h":[15,300],"seat_h":None},
 "monitor":          {"w":[280,900],"d":[100,360],"h":[250,700],"seat_h":None},
 "appliance":        {"w":[100,800],"d":[100,800],"h":[60,1500],"seat_h":None},
 "rack":             {"w":[250,1600],"d":[250,900],"h":[120,1900],"seat_h":None},
 "cushion":          {"w":[300,1300],"d":[300,1300],"h":[100,900],"seat_h":None},
 "bike":             {"w":[350,1900],"d":[250,700],"h":[600,1250],"seat_h":None},
 "curtain_rod":      {"w":[400,3000],"d":[40,200],"h":[20,150],"seat_h":None},
 "string_lights":    {"w":[1000,6000],"d":[20,250],"h":[100,1200],"seat_h":None},
}
