# -*- coding: utf-8 -*-
"""Renders one 192x192 transparent isometric thumbnail per catalog item (SPEC2 §I1)
and emits the `file://`-safe ES module the browser list consumes.

    python3 tools/gen_thumbs.py                 # thumbs/*.png + thumbs.js
    python3 tools/gen_thumbs.py --grid 48       # also writes thumbs_grid_48.png for review
    python3 tools/gen_thumbs.py --only ai-      # id prefix filter

Same projector, camera and light as tools/contact_sheet.py -- every tile is the identical
30-degree isometric with the light coming from +x/+y/+z, so the set reads as one family.
Output PNGs are octree-quantised (<=48 colours + alpha) to keep each data URI small; the
demo can't fetch() local files from file://, hence the module.
"""
import argparse
import base64
import json
import os
import sys

from PIL import Image, ImageDraw, ImageFilter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import contact_sheet as CS  # projector + colour resolution, reused verbatim

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SS = 4              # supersample factor
FILL = 0.86         # fraction of the tile the item's bbox spans
SHADOW = (12, 14, 18)


def render_thumb(item, px=192):
    T = px * SS
    img = Image.new("RGBA", (T, T), (0, 0, 0, 0))
    ops, (x0, y0, x1, y1) = CS.collect(item, T)

    # ---- ground shadow footprint, included in the framing bbox
    w, d = item["dims_mm"]["w"], item["dims_mm"]["d"]
    gp = [CS.proj(sx * w / 2.0, sy * d / 2.0, 0) for (sx, sy) in ((-1, -1), (1, -1), (1, 1), (-1, 1))]
    gx = [p[0] for p in gp] + [x0, x1]
    gy = [p[1] for p in gp] + [y0, y1]
    x0, x1, y0, y1 = min(gx), max(gx), min(gy), max(gy)

    span = max(x1 - x0, y1 - y0, 1)
    s = (T * FILL) / span
    cx, cy = (x0 + x1) / 2.0, (y0 + y1) / 2.0
    ox = oy = T / 2.0
    to = lambda p: ((p[0] - cx) * s + ox, (p[1] - cy) * s + oy)

    shadow = Image.new("L", (T, T), 0)
    ImageDraw.Draw(shadow).polygon([to(p) for p in gp], fill=104)
    shadow = shadow.filter(ImageFilter.GaussianBlur(T * 0.022))
    img.paste(Image.new("RGBA", (T, T), SHADOW + (255,)), (0, 0), shadow)

    dr = ImageDraw.Draw(img)
    for dep, pts, col in ops:
        poly = [to(p) for p in pts]
        dr.polygon(poly, fill=col + (255,), outline=CS.shade(col, 0.66) + (255,))

    return img.resize((px, px), Image.LANCZOS)


def quantise(img, colors=48):
    """Indexed PNG with a 1-bit alpha cutout -- ~10x smaller than RGBA, and the silhouette
    is hard-edged anyway because the projector draws flat polygons."""
    alpha = img.getchannel("A").point(lambda a: 255 if a >= 128 else 0)
    rgb = img.convert("RGB").quantize(colors=colors - 1, method=Image.FASTOCTREE)
    rgb.info["transparency"] = colors - 1
    pal = rgb.convert("RGB")
    out = Image.new("RGB", img.size, (0, 0, 0))
    out.paste(pal, (0, 0))
    q = out.quantize(colors=colors - 1, method=Image.FASTOCTREE)
    # append a dedicated transparent index
    q = q.convert("P", palette=Image.ADAPTIVE, colors=colors - 1)
    q.paste(colors - 1, Image.eval(alpha, lambda a: 255 - a).convert("1"))
    p = q.getpalette() or []
    p = (p + [0] * (768 - len(p)))[:768]
    q.putpalette(p)
    q.info["transparency"] = colors - 1
    return q


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--px", type=int, default=192)
    ap.add_argument("--colors", type=int, default=48)
    ap.add_argument("--only", default=None, help="id prefix filter")
    ap.add_argument("--grid", type=int, default=0, help="also write a NxN review grid at this tile size")
    args = ap.parse_args()

    cat = json.load(open(os.path.join(ROOT, "catalog.json"), encoding="utf-8"))
    items = cat["items"]
    if args.only:
        items = [i for i in items if i["id"].startswith(args.only)]

    outdir = os.path.join(ROOT, "thumbs")
    os.makedirs(outdir, exist_ok=True)

    entries, sizes, small = [], [], []
    for it in items:
        img = render_thumb(it, args.px)
        q = quantise(img, args.colors)
        path = os.path.join(outdir, it["id"] + ".png")
        q.save(path, optimize=True)
        raw = open(path, "rb").read()
        sizes.append((len(raw), it["id"]))
        entries.append('  "%s": "data:image/png;base64,%s"' % (it["id"], base64.b64encode(raw).decode()))
        if args.grid:
            small.append((it["id"], img.resize((args.grid, args.grid), Image.LANCZOS)))

    js = ("// ainterior :: packages/catalog/thumbs.js\n"
          "// Generated by tools/gen_thumbs.py -- DO NOT EDIT BY HAND.\n"
          "// %d isometric proxy thumbnails, %dx%d, transparent, indexed PNG.\n"
          "// Inlined as data URIs because the demo runs from file://, where fetch() of\n"
          "// local files is blocked.\n"
          "export const THUMBS = {\n%s\n};\n\nexport default THUMBS;\n"
          % (len(entries), args.px, args.px, ",\n".join(entries)))
    jspath = os.path.join(ROOT, "thumbs.js")
    open(jspath, "w", encoding="utf-8").write(js)

    sizes.sort(reverse=True)
    total = sum(s for s, _ in sizes)
    print("thumbs      : %d -> %s" % (len(sizes), outdir))
    print("png bytes   : total %.1f KB  avg %d B  max %d B (%s)"
          % (total / 1024.0, total / max(1, len(sizes)), sizes[0][0], sizes[0][1]))
    print("over 4KB    : %d      over 8KB: %d" % (sum(1 for s, _ in sizes if s > 4096),
                                                  sum(1 for s, _ in sizes if s > 8192)))
    print("thumbs.js   : %.1f KB" % (os.path.getsize(jspath) / 1024.0))

    if args.grid:
        cols = 24
        g = args.grid
        pad = 6
        rows = (len(small) + cols - 1) // cols
        sheet = Image.new("RGB", (cols * (g + pad) + pad, rows * (g + pad) + pad), (26, 26, 30))
        for n, (_id, im) in enumerate(small):
            r, c = divmod(n, cols)
            sheet.paste(im, (pad + c * (g + pad), pad + r * (g + pad)), im)
        gp = os.path.join(ROOT, "thumbs_grid_%d.png" % g)
        sheet.save(gp)
        print("grid        : %s (%dx%d)" % (gp, sheet.size[0], sheet.size[1]))


if __name__ == "__main__":
    main()
