# -*- coding: utf-8 -*-
"""Source-of-truth item table for the ainterior IKEA catalog.

Dimensions are millimetres, integers (SPEC v1 §1).
`conf` is dims_confidence: "high" | "medium" | "low"  -- see CATALOG.md §Provenance.
Fields: id, name, product_type, cat, arch, w, d, h, seat_h, price_usd, conf, footprint,
        palette key, tags, note
"""

# ---------------------------------------------------------------- colour palettes
P = {
    "sofa_beige":  [("Totebo light beige", "#D8D2C4"), ("Hallarp beige", "#CFC6B4"), ("Vittaryd white", "#EDE9E2")],
    "sofa_gray":   [("Tallmyra gray", "#8E9095"), ("Gunnared medium gray", "#7E8288"), ("Tibbleby beige/gray", "#B6AFA2")],
    "sofa_blue":   [("Tallmyra blue", "#4E6076"), ("Gunnared blue", "#5A6B7C")],
    "sofa_dark":   [("Grann dark brown", "#4A3B31"), ("Bomstad black", "#26241F")],
    "poang":       [("Birch veneer / Knisa light beige", "#D9CBB2"), ("Black-brown / Hillared anthracite", "#3A3A3C")],
    "wing":        [("Nordvalla dark gray", "#5C5F63"), ("Skiftebo yellow", "#C6912F"), ("Kelinge gray-turquoise", "#5C7C7B")],
    "wood_oak":    [("Oak veneer", "#C7A87A"), ("White stained oak", "#DED3C0")],
    "wood_birch":  [("Birch veneer", "#DCC49C")],
    "wood_pine":   [("Untreated solid pine", "#D8BE93")],
    "wood_ash":    [("Ash veneer", "#D5C1A1")],
    "wood_acacia": [("Acacia", "#8C6239")],
    "white":       [("White", "#F2F1EE")],
    "white_bb":    [("White", "#F2F1EE"), ("Black-brown", "#33291F")],
    "bb":          [("Black-brown", "#33291F")],
    "white_oak":   [("White", "#F2F1EE"), ("Oak effect", "#C7A87A"), ("Black-brown", "#33291F")],
    "gray_stain":  [("Gray stained", "#8B8579"), ("White stained", "#DED3C0")],
    "metal_black": [("Black", "#1E1E20"), ("Anthracite", "#2E2E31")],
    "metal_white": [("White", "#F2F1EE"), ("Nickel plated", "#B9BDC2")],
    "metal_dark":  [("Dark gray", "#3B3D40"), ("Off-white", "#E6E2D9")],
    "glass_black": [("Black-brown / glass", "#2B2B2E")],
    "leather_bl":  [("Glose black leather", "#232326"), ("Grann dark brown leather", "#4A3B31")],
    "rug_offwhite":[("Off-white", "#E9E4DA"), ("Light beige", "#DCD3C2")],
    "rug_gray":    [("Gray", "#8D8F92"), ("Dark blue", "#3B4A61")],
    "rug_natural": [("Natural / beige", "#CFC0A4"), ("Black/white", "#4A4A4A")],
    "plant":       [("Green", "#4C7A45")],
    "curtain":     [("White", "#F2F1EE"), ("Light gray", "#C9C6C0"), ("Dark blue", "#2E3C51")],
    "tv":          [("Black", "#141416")],
}

# id, name, product_type, cat, arch, w, d, h, seat_h, price, conf, footprint, palette, tags, note
ITEMS = [
# ============================================================ SEATING — sofas
("ikea-ektorp-3seat","EKTORP","3-seat sofa","seating","sofa_3seat",2180,880,880,450,649,"high","rect","sofa_beige",["living-room","upholstered","family","washable-cover"],""),
("ikea-ektorp-2seat","EKTORP","2-seat sofa","seating","sofa_2seat",1790,880,880,450,529,"medium","rect","sofa_beige",["living-room","upholstered","family"],"2-seat width interpolated from the 3-seat/armchair family module pitch."),
("ikea-ektorp-armchair","EKTORP","Armchair","seating","armchair",1040,880,880,450,349,"medium","rect","sofa_beige",["living-room","upholstered"],""),
("ikea-kivik-3seat","KIVIK","3-seat sofa","seating","sofa_3seat",2280,950,830,450,899,"high","rect","sofa_gray",["living-room","upholstered","deep-seat"],""),
("ikea-kivik-2seat","KIVIK","2-seat sofa","seating","sofa_2seat",1900,950,830,450,749,"medium","rect","sofa_gray",["living-room","upholstered","deep-seat"],""),
("ikea-kivik-chaise-sectional","KIVIK","4-seat sofa with chaise longue","seating","sofa_sectional_l",2800,1630,830,450,1499,"medium","L","sofa_gray",["living-room","upholstered","sectional"],"Chaise depth (1630) confident; overall width varies by module order."),
("ikea-soderhamn-3seat","SÖDERHAMN","3-seat sofa","seating","sofa_3seat",1980,990,830,400,949,"high","rect","sofa_gray",["living-room","low-back","modular"],""),
("ikea-soderhamn-armchair","SÖDERHAMN","Armchair","seating","armchair",1050,990,830,400,399,"medium","rect","sofa_gray",["living-room","low-back","modular"],""),
("ikea-soderhamn-chaise","SÖDERHAMN","Chaise longue","seating","chaise",1870,990,830,400,549,"medium","rect","sofa_gray",["living-room","modular"],""),
("ikea-landskrona-3seat","LANDSKRONA","3-seat sofa","seating","sofa_3seat",2040,890,780,440,1099,"medium","rect","leather_bl",["living-room","leather","mid-century"],"Height/seat height from the leather variant; fabric variant may differ ±20mm."),
("ikea-landskrona-2seat","LANDSKRONA","2-seat sofa","seating","sofa_2seat",1640,890,780,440,899,"medium","rect","leather_bl",["living-room","leather","mid-century"],""),
("ikea-landskrona-armchair","LANDSKRONA","Armchair","seating","armchair",890,890,780,440,549,"medium","rect","leather_bl",["living-room","leather"],""),
("ikea-friheten-corner-sofabed","FRIHETEN","Corner sofa-bed with storage","seating","sofa_sectional_l",2300,1510,660,450,899,"medium","L","sofa_dark",["living-room","sofa-bed","storage","small-space"],"Seat height approximate; back height 660 is the low-back silhouette."),
("ikea-vimle-3seat","VIMLE","3-seat sofa","seating","sofa_3seat",2410,980,830,450,1099,"medium","rect","sofa_gray",["living-room","modular","upholstered"],""),
("ikea-klippan-loveseat","KLIPPAN","Loveseat","seating","loveseat",1800,880,660,430,349,"high","rect","sofa_gray",["living-room","small-space","compact"],""),
("ikea-gronlid-3seat","GRÖNLID","3-seat sofa","seating","sofa_3seat",2490,980,1040,470,1299,"medium","rect","sofa_beige",["living-room","high-back","modular"],""),
# ============================================================ SEATING — chairs
("ikea-poang-armchair","POÄNG","Armchair","seating","armchair",680,820,1000,420,169,"high","rect","poang",["living-room","bentwood","classic"],""),
("ikea-poang-footstool","POÄNG","Footstool","seating","ottoman",680,540,390,390,79,"medium","rect","poang",["living-room","footstool"],""),
("ikea-strandmon-wing-chair","STRANDMON","Wing chair","seating","armchair",820,960,1010,450,399,"high","rect","wing",["living-room","wing-chair","reading"],""),
("ikea-strandmon-footstool","STRANDMON","Footstool","seating","ottoman",680,530,450,450,149,"medium","rect","wing",["living-room","footstool"],""),
("ikea-pello-armchair","PELLO","Armchair","seating","armchair",670,820,940,420,79,"medium","rect","poang",["living-room","bentwood","budget"],""),
("ikea-tullsta-armchair","TULLSTA","Armchair","seating","armchair",790,690,780,450,199,"medium","rect","sofa_beige",["living-room","compact","upholstered"],""),
("ikea-vedbo-armchair","VEDBO","Armchair","seating","armchair",680,760,850,450,299,"low","rect","sofa_gray",["living-room","upholstered"],"Dimensions estimated from product photography ratios — verify before commercial use."),
("ikea-landskrona-footstool","LANDSKRONA","Footstool","seating","ottoman",780,640,440,440,249,"medium","rect","leather_bl",["living-room","footstool","leather"],""),
("ikea-ektorp-footstool","EKTORP","Footstool","seating","ottoman",800,640,430,430,179,"low","rect","sofa_beige",["living-room","footstool"],"Footstool dimensions inferred from the sofa family; low confidence."),
("ikea-ekedalen-chair","EKEDALEN","Chair","seating","dining_chair",430,510,950,470,89,"medium","rect","wood_oak",["dining-room","upholstered-seat"],""),
("ikea-ingolf-chair","INGOLF","Chair","seating","dining_chair",400,520,910,450,79,"high","rect","white_bb",["dining-room","solid-wood","traditional"],""),
("ikea-stefan-chair","STEFAN","Chair","seating","dining_chair",430,490,900,450,45,"high","rect","bb",["dining-room","solid-wood","budget"],""),
("ikea-teodores-chair","TEODORES","Chair","seating","dining_chair",450,510,820,450,45,"medium","rect","white_bb",["dining-room","plastic","stackable"],""),
("ikea-adde-chair","ADDE","Chair","seating","dining_chair",390,470,770,450,20,"high","rect","metal_black",["dining-room","stackable","budget"],""),
("ikea-janinge-chair","JANINGE","Chair","seating","dining_chair",500,460,760,460,60,"medium","rect","white_bb",["dining-room","plastic","stackable"],""),
("ikea-odger-chair","ODGER","Chair","seating","dining_chair",550,510,810,450,80,"medium","rect","gray_stain",["dining-room","recycled","molded"],""),
("ikea-norraker-chair","NORRÅKER","Chair","seating","dining_chair",470,530,830,450,110,"low","rect","wood_birch",["dining-room","solid-wood"],"Seat/back geometry from photos; width and depth low confidence."),
("ikea-markus-office-chair","MARKUS","Office chair","seating","office_chair",620,600,1400,470,269,"high","rect","metal_dark",["office","high-back","ergonomic","mesh","round-base"],"Total height is adjustable 1290–1400; stored value is max."),
("ikea-millberget-swivel-chair","MILLBERGET","Swivel chair","seating","office_chair",630,600,1050,470,109,"medium","rect","white_bb",["office","swivel","compact","round-base"],"Height adjustable ~950–1050."),
("ikea-langfjall-office-chair","LÅNGFJÄLL","Office chair","seating","office_chair",680,680,1040,460,299,"medium","rect","metal_dark",["office","ergonomic","upholstered","round-base"],""),
("ikea-flintan-office-chair","FLINTAN","Office chair","seating","office_chair",640,640,970,450,99,"medium","rect","metal_black",["office","budget","swivel","round-base"],""),
("ikea-marius-stool","MARIUS","Stool","seating","stool",320,320,450,450,10,"high","round","metal_black",["kitchen","stackable","budget"],""),
("ikea-frosta-stool","FROSTA","Stool","seating","stool",350,350,450,450,25,"high","round","wood_birch",["kitchen","stackable","bentwood"],""),
("ikea-ingolf-bar-stool","INGOLF","Bar stool with backrest","seating","bar_stool",400,450,910,740,109,"high","rect","white_bb",["kitchen","counter","solid-wood"],"Overall height 910, seat height 740."),
("ikea-franklin-bar-stool","FRANKLIN","Foldable bar stool","seating","bar_stool",400,450,950,740,45,"medium","rect","metal_black",["kitchen","foldable","counter"],""),
("ikea-skogsta-bench","SKOGSTA","Bench","seating","bench",1200,400,450,450,149,"medium","rect","wood_acacia",["dining-room","entry","solid-wood"],""),
("ikea-mackapar-bench","MACKAPÄR","Bench with shoe storage","seating","bench",1000,510,500,500,99,"low","rect","white",["entry","hallway","storage"],"Depth/height estimated; verify against current spec sheet."),
# ============================================================ TABLES
("ikea-lack-coffee-table","LACK","Coffee table","tables","coffee_table",900,550,450,None,45,"high","rect","white_bb",["living-room","budget","lightweight"],""),
("ikea-lack-side-table","LACK","Side table","tables","side_table",550,550,450,None,15,"high","rect","white_bb",["living-room","budget","lightweight"],""),
("ikea-vittsjo-coffee-table","VITTSJÖ","Coffee table","tables","coffee_table",900,500,450,None,80,"medium","rect","glass_black",["living-room","glass","metal"],""),
("ikea-lisabo-coffee-table","LISABO","Coffee table","tables","coffee_table",1180,500,450,None,149,"medium","rect","wood_ash",["living-room","solid-wood","scandinavian"],""),
("ikea-kragsta-coffee-table","KRAGSTA","Coffee table","tables","coffee_table",900,900,450,None,99,"medium","round","metal_black",["living-room","round","nesting"],""),
("ikea-hemnes-coffee-table","HEMNES","Coffee table","tables","coffee_table",1180,750,460,None,229,"medium","rect","white_bb",["living-room","solid-wood","traditional"],""),
("ikea-stockholm-coffee-table","STOCKHOLM","Coffee table","tables","coffee_table",1800,590,400,None,399,"low","rect","wood_oak",["living-room","premium","walnut"],"Long-run collection; dimensions vary between editions."),
("ikea-gladom-tray-table","GLADOM","Tray table","tables","side_table",450,450,530,None,35,"medium","round","metal_dark",["living-room","tray","portable"],""),
("ikea-burvik-side-table","BURVIK","Side table","tables","side_table",380,380,680,None,45,"medium","round","metal_white",["living-room","round","compact"],""),
("ikea-lisabo-side-table","LISABO","Side table","tables","side_table",500,500,500,None,79,"medium","round","wood_ash",["living-room","solid-wood","round"],""),
("ikea-lunnarp-side-table","LUNNARP","Side table","tables","side_table",550,450,600,None,79,"low","rect","white_bb",["living-room","drawer"],"Estimated from photos."),
("ikea-ingatorp-round-ext-table","INGATORP","Extendable round table","tables","dining_table_round",1100,1100,740,None,399,"high","round","white_bb",["dining-room","extendable","traditional"],"Extends to 1550 on the long axis; stored value is closed diameter."),
("ikea-ekedalen-ext-table","EKEDALEN","Extendable table","tables","dining_table_rect",1200,800,750,None,299,"high","rect","white_bb",["dining-room","extendable"],"Extends 1200→1800."),
("ikea-norden-gateleg-table","NORDEN","Gateleg table","tables","dining_table_rect",890,800,750,None,299,"high","rect","wood_birch",["dining-room","small-space","folding","storage"],"Folds 260 / 890 / 1520; stored value is the single-leaf state."),
("ikea-norden-dining-table","NORDEN","Dining table","tables","dining_table_rect",2200,1000,750,None,499,"medium","rect","wood_birch",["dining-room","solid-wood","large"],""),
("ikea-lisabo-dining-table","LISABO","Table","tables","dining_table_rect",1400,780,740,None,229,"high","rect","wood_ash",["dining-room","solid-wood","scandinavian"],""),
("ikea-skogsta-dining-table","SKOGSTA","Dining table","tables","dining_table_rect",2350,1000,750,None,599,"high","rect","wood_acacia",["dining-room","solid-wood","large"],""),
("ikea-morbylanga-table","MÖRBYLÅNGA","Table","tables","dining_table_rect",2200,1000,740,None,699,"medium","rect","wood_oak",["dining-room","oak-veneer","large"],""),
("ikea-ingo-table","INGO","Table","tables","dining_table_rect",1200,750,750,None,79,"high","rect","wood_pine",["dining-room","budget","solid-pine"],""),
("ikea-melltorp-table","MELLTORP","Table","tables","dining_table_rect",1250,750,720,None,99,"high","rect","white",["dining-room","budget","laminate"],""),
("ikea-vangsta-ext-table","VANGSTA","Extendable table","tables","dining_table_rect",1200,750,730,None,149,"medium","rect","white_bb",["dining-room","extendable","small-space"],"Extends 1200→1800."),
("ikea-laneberg-ext-table","LANEBERG","Extendable table","tables","dining_table_rect",1300,800,750,None,279,"medium","rect","white_bb",["dining-room","extendable"],"Extends 1300→1900."),
("ikea-strandtorp-ext-table","STRANDTORP","Extendable table","tables","dining_table_rect",1500,950,750,None,549,"medium","rect","bb",["dining-room","extendable","large"],"Extends 1500→2600 in two steps."),
("ikea-docksta-round-table","DOCKSTA","Table","tables","dining_table_round",1050,1050,750,None,229,"high","round","white",["dining-room","round","pedestal","tulip"],""),
("ikea-havsta-console-table","HAVSTA","Console table","tables","console_table",1000,350,750,None,199,"low","rect","white_bb",["living-room","hallway","entry"],"Console dimensions estimated; IKEA console line-up changes frequently."),
("ikea-idanas-console-table","IDANÄS","Console table","tables","console_table",1310,400,820,None,249,"low","rect","white_bb",["living-room","hallway","drawers"],"Estimated; verify before quoting to a client."),
("ikea-stenstorp-kitchen-island","STENSTORP","Kitchen island","tables","kitchen_island",1260,790,900,None,599,"medium","rect","white_oak",["kitchen","island","oak-top","storage"],""),
("ikea-tornviken-kitchen-island","TORNVIKEN","Kitchen island","tables","kitchen_island",1260,770,900,None,649,"medium","rect","white_oak",["kitchen","island","open-shelf"],""),
("ikea-vadholma-kitchen-island","VADHOLMA","Kitchen island","tables","kitchen_island",1260,790,900,None,749,"low","rect","bb",["kitchen","island","rack"],"Estimated from the STENSTORP/TORNVIKEN island module width."),
("ikea-applaro-outdoor-table","ÄPPLARÖ","Outdoor table","outdoor","dining_table_rect",1400,800,720,None,229,"medium","rect","wood_acacia",["outdoor","patio","acacia"],""),
("ikea-tarno-outdoor-chair","TÄRNÖ","Outdoor folding chair","outdoor","dining_chair",470,540,780,450,30,"low","rect","wood_acacia",["outdoor","folding","budget"],"Estimated; folding geometry approximated as a fixed chair."),
# ============================================================ DESKS
("ikea-micke-desk-105","MICKE","Desk","desks","desk",1050,500,750,None,99,"high","rect","white_bb",["office","compact","drawer"],""),
("ikea-micke-desk-142","MICKE","Desk","desks","desk",1420,500,750,None,169,"medium","rect","white_bb",["office","drawer"],""),
("ikea-linnmon-adils-120","LINNMON / ADILS","Table top with legs","desks","desk",1200,600,740,None,60,"high","rect","white_bb",["office","budget","modular"],""),
("ikea-linnmon-adils-150","LINNMON / ADILS","Table top with legs","desks","desk",1500,750,740,None,85,"medium","rect","white_bb",["office","budget","modular"],""),
("ikea-lagkapten-adils-140","LAGKAPTEN / ADILS","Desk","desks","desk",1400,600,730,None,80,"medium","rect","white_oak",["office","modular"],""),
("ikea-malm-desk","MALM","Desk","desks","desk",1400,650,730,None,199,"medium","rect","white_bb",["bedroom","office","veneer"],""),
("ikea-bekant-desk-160","BEKANT","Desk","desks","desk",1600,800,800,None,249,"high","rect","metal_white",["office","commercial","adjustable"],"Height adjustable 650–850; stored value is a mid setting."),
("ikea-trotten-desk-120","TROTTEN","Desk","desks","desk",1200,700,750,None,169,"medium","rect","metal_white",["office","commercial"],""),
("ikea-alex-desk","ALEX","Desk","desks","desk",1320,580,760,None,229,"medium","rect","white_bb",["office","drawers","studio"],""),
("ikea-hemnes-desk","HEMNES","Desk","desks","desk",1550,650,740,None,349,"medium","rect","white_bb",["office","solid-wood","traditional"],""),
("ikea-vittsjo-laptop-table","VITTSJÖ","Laptop table","desks","desk",1000,360,740,None,60,"medium","rect","glass_black",["office","narrow","glass"],""),
("ikea-utespelare-gaming-desk","UTESPELARE","Gaming desk","desks","desk",1600,800,730,None,229,"medium","rect","metal_black",["office","gaming"],""),
("ikea-alex-drawer-unit","ALEX","Drawer unit","storage","cabinet",360,580,700,None,129,"medium","rect","white_bb",["office","drawers","under-desk"],""),
# ============================================================ BEDS
("ikea-malm-bed-queen","MALM","Bed frame, high","beds","bed_queen",1580,2090,1000,380,399,"high","rect","white_oak",["bedroom","veneer","classic"],"Queen (US) frame; headboard height 1000, platform ~380."),
("ikea-malm-bed-king","MALM","Bed frame, high","beds","bed_king",1930,2110,1000,380,499,"medium","rect","white_oak",["bedroom","veneer","classic"],""),
("ikea-malm-bed-full","MALM","Bed frame, high","beds","bed_double",1380,2090,1000,380,349,"medium","rect","white_oak",["bedroom","veneer","classic"],""),
("ikea-malm-bed-twin","MALM","Bed frame, high","beds","bed_single",980,2090,1000,380,279,"medium","rect","white_oak",["bedroom","veneer","kids"],""),
("ikea-hemnes-bed-queen","HEMNES","Bed frame","beds","bed_queen",1660,2110,1200,410,449,"medium","rect","white_bb",["bedroom","solid-wood","traditional"],"Headboard height 1200 from the solid-pine variant."),
("ikea-brimnes-bed-queen","BRIMNES","Bed frame with storage & headboard","beds","bed_queen",1660,2060,1110,400,449,"medium","rect","white_bb",["bedroom","storage","headboard-shelf"],""),
("ikea-slattum-bed-queen","SLATTUM","Upholstered bed frame","beds","bed_queen",1570,2120,860,340,279,"medium","rect","sofa_gray",["bedroom","upholstered","low"],""),
("ikea-tarva-bed-queen","TARVA","Bed frame","beds","bed_queen",1680,2090,920,380,249,"low","rect","wood_pine",["bedroom","solid-pine","unfinished"],"Solid-pine frame; overall width low confidence."),
("ikea-songesand-bed-queen","SONGESAND","Bed frame","beds","bed_queen",1680,2110,950,400,299,"low","rect","white_bb",["bedroom","traditional"],"Estimated."),
("ikea-idanas-bed-queen","IDANÄS","Upholstered bed frame","beds","bed_queen",1680,2140,1220,400,549,"low","rect","sofa_gray",["bedroom","upholstered","high-headboard"],"Estimated from photography; verify."),
("ikea-hauga-bed-queen","HAUGA","Upholstered bed frame with storage","beds","bed_queen",1680,2110,1370,400,499,"low","rect","sofa_beige",["bedroom","upholstered","storage"],"Estimated."),
("ikea-neiden-bed-twin","NEIDEN","Bed frame","beds","bed_single",980,2070,700,300,89,"medium","rect","wood_pine",["bedroom","budget","solid-pine"],""),
("ikea-brimnes-daybed","BRIMNES","Daybed with 2 drawers","beds","bed_single",870,2070,1000,470,349,"low","rect","white",["bedroom","guest","storage","daybed"],"Daybed converts to a double; stored footprint is the single state."),
("ikea-kura-reversible-bed","KURA","Reversible bed","kids","bed_single",990,2090,1160,300,229,"medium","rect","wood_pine",["kids","loft","reversible"],"Reversible: platform sits at ~300mm one way up, ~900mm as a loft. Stored seat_h_mm is the low orientation."),
("ikea-sniglar-crib","SNIGLAR","Crib","kids","crib",670,1240,800,None,99,"medium","rect","wood_birch",["kids","nursery","beech"],""),
("ikea-sundvik-crib","SUNDVIK","Crib","kids","crib",700,1270,840,None,169,"low","rect","white_bb",["kids","nursery"],"Estimated from the SNIGLAR/GULLIVER crib family."),
# ============================================================ STORAGE — nightstands / dressers
("ikea-malm-nightstand","MALM","2-drawer chest","storage","nightstand",400,480,550,None,79,"high","rect","white_oak",["bedroom","nightstand","drawers"],""),
("ikea-hemnes-nightstand","HEMNES","2-drawer nightstand","storage","nightstand",460,350,700,None,129,"high","rect","white_bb",["bedroom","nightstand","solid-wood"],""),
("ikea-knarrevik-nightstand","KNARREVIK","Nightstand","storage","nightstand",370,280,510,None,15,"high","rect","metal_black",["bedroom","nightstand","budget","compact"],""),
("ikea-brimnes-nightstand","BRIMNES","Nightstand","storage","nightstand",390,410,530,None,60,"medium","rect","white_bb",["bedroom","nightstand","glass-door"],""),
("ikea-vikhammer-nightstand","VIKHAMMER","Nightstand","storage","nightstand",400,390,600,None,99,"low","rect","metal_black",["bedroom","nightstand","metal"],"Estimated."),
("ikea-malm-6drawer-chest","MALM","6-drawer chest","storage","dresser",800,480,1230,None,299,"high","rect","white_oak",["bedroom","dresser","tall"],""),
("ikea-malm-3drawer-chest","MALM","3-drawer chest","storage","dresser",800,480,780,None,179,"high","rect","white_oak",["bedroom","dresser"],""),
("ikea-malm-4drawer-chest","MALM","4-drawer chest","storage","dresser",800,480,1000,None,229,"medium","rect","white_oak",["bedroom","dresser"],""),
("ikea-hemnes-8drawer-chest","HEMNES","8-drawer chest","storage","dresser",1080,500,1310,None,449,"medium","rect","white_bb",["bedroom","dresser","solid-wood","tall"],""),
("ikea-hemnes-3drawer-chest","HEMNES","3-drawer chest","storage","dresser",1080,500,950,None,329,"medium","rect","white_bb",["bedroom","dresser","solid-wood"],""),
("ikea-koppang-3drawer-chest","KOPPANG","3-drawer chest","storage","dresser",900,460,830,None,199,"medium","rect","white_bb",["bedroom","dresser"],""),
("ikea-kullen-5drawer-chest","KULLEN","5-drawer chest","storage","dresser",700,400,1120,None,99,"medium","rect","bb",["bedroom","dresser","budget","tall"],""),
("ikea-nordli-6drawer-chest","NORDLI","6-drawer chest","storage","dresser",800,470,990,None,349,"medium","rect","white_bb",["bedroom","dresser","modular","handleless"],""),
("ikea-brimnes-4drawer-chest","BRIMNES","4-drawer chest","storage","dresser",780,460,1240,None,179,"medium","rect","white",["bedroom","dresser","tall"],""),
("ikea-tarva-5drawer-chest","TARVA","5-drawer chest","storage","dresser",790,390,1250,None,199,"low","rect","wood_pine",["bedroom","dresser","solid-pine"],"Estimated."),
# ============================================================ STORAGE — wardrobes
("ikea-pax-wardrobe-150","PAX","Wardrobe","storage","wardrobe",1500,580,2010,None,499,"high","rect","white_oak",["bedroom","wardrobe","modular"],""),
("ikea-pax-wardrobe-200-236","PAX","Wardrobe","storage","wardrobe",2000,580,2360,None,799,"high","rect","white_oak",["bedroom","wardrobe","modular","tall"],""),
("ikea-pax-wardrobe-100","PAX","Wardrobe","storage","wardrobe",1000,580,2010,None,349,"high","rect","white_oak",["bedroom","wardrobe","modular"],""),
("ikea-brimnes-wardrobe-3door","BRIMNES","Wardrobe with 3 doors","storage","wardrobe",1170,500,1900,None,299,"medium","rect","white",["bedroom","wardrobe","mirror-door"],""),
("ikea-hemnes-wardrobe-3door","HEMNES","Wardrobe with 3 doors","storage","wardrobe",1520,590,1970,None,699,"medium","rect","white_bb",["bedroom","wardrobe","solid-wood"],""),
("ikea-kleppstad-wardrobe-2door","KLEPPSTAD","Wardrobe with 2 doors","storage","wardrobe",790,550,1760,None,149,"medium","rect","white_bb",["bedroom","wardrobe","budget","compact"],""),
("ikea-nordkisa-open-wardrobe","NORDKISA","Open wardrobe with sliding door","storage","wardrobe",1200,470,1230,None,229,"medium","rect","wood_birch",["bedroom","open-wardrobe","bamboo"],""),
# ============================================================ STORAGE — bookcases / shelf units
("ikea-billy-bookcase-80","BILLY","Bookcase","storage","bookcase",800,280,2020,None,69,"high","rect","white_oak",["living-room","bookcase","classic"],""),
("ikea-billy-bookcase-40","BILLY","Bookcase","storage","bookcase",400,280,2020,None,50,"high","rect","white_oak",["living-room","bookcase","narrow"],""),
("ikea-billy-bookcase-80-low","BILLY","Bookcase","storage","bookcase",800,280,1060,None,55,"high","rect","white_oak",["living-room","bookcase","low"],""),
("ikea-hemnes-bookcase","HEMNES","Bookcase","storage","bookcase",900,370,1970,None,229,"medium","rect","white_bb",["living-room","bookcase","solid-wood"],""),
("ikea-gersby-bookcase","GERSBY","Bookcase","storage","bookcase",600,240,1800,None,35,"medium","rect","white_bb",["living-room","bookcase","budget"],""),
("ikea-laiva-bookcase","LAIVA","Bookcase","storage","bookcase",620,240,1650,None,25,"medium","rect","bb",["living-room","bookcase","budget"],""),
("ikea-fjalkinge-shelf-unit","FJÄLKINGE","Shelf unit","storage","shelf_unit",1180,350,1930,None,249,"medium","rect","white",["living-room","shelving","metal","industrial"],""),
("ikea-ivar-1section","IVAR","1 section shelving unit","storage","shelf_unit",890,300,1790,None,120,"medium","rect","wood_pine",["storage","utility","solid-pine","modular"],""),
("ikea-kallax-4x4","KALLAX","Shelf unit","storage","shelf_unit",1470,390,1470,None,199,"high","rect","white_oak",["living-room","cube-storage","room-divider"],""),
("ikea-kallax-2x4","KALLAX","Shelf unit","storage","shelf_unit",770,390,1470,None,109,"high","rect","white_oak",["living-room","cube-storage"],""),
("ikea-kallax-2x2","KALLAX","Shelf unit","storage","shelf_unit",770,390,770,None,79,"high","rect","white_oak",["living-room","cube-storage","low"],""),
("ikea-kallax-1x4","KALLAX","Shelf unit","storage","shelf_unit",420,390,1470,None,79,"high","rect","white_oak",["living-room","cube-storage","narrow"],""),
("ikea-kallax-5x5","KALLAX","Shelf unit","storage","shelf_unit",1820,390,1820,None,279,"medium","rect","white_oak",["living-room","cube-storage","large","room-divider"],""),
# ============================================================ STORAGE — sideboards / cabinets / tv
("ikea-besta-tv-bench-180","BESTÅ","TV bench","storage","tv_bench",1800,420,380,None,199,"high","rect","white_oak",["living-room","tv","modular","low"],""),
("ikea-besta-tv-bench-120","BESTÅ","TV bench with doors","storage","tv_bench",1200,420,640,None,229,"medium","rect","white_oak",["living-room","tv","modular"],""),
("ikea-besta-storage-combination","BESTÅ","Storage combination with doors","storage","sideboard",1800,420,740,None,399,"medium","rect","white_oak",["living-room","sideboard","modular"],""),
("ikea-lack-tv-bench","LACK","TV bench","storage","tv_bench",900,260,450,None,40,"medium","rect","white_bb",["living-room","tv","budget"],""),
("ikea-hemnes-tv-bench","HEMNES","TV bench","storage","tv_bench",1480,470,570,None,299,"medium","rect","white_bb",["living-room","tv","solid-wood"],""),
("ikea-brimnes-tv-bench","BRIMNES","TV bench","storage","tv_bench",1800,410,530,None,169,"medium","rect","white_bb",["living-room","tv","glass-door"],""),
("ikea-havsta-sideboard","HAVSTA","Sideboard","storage","sideboard",1620,470,880,None,499,"low","rect","white_bb",["living-room","dining-room","sideboard"],"Estimated from the HAVSTA module grid."),
("ikea-ivar-cabinet","IVAR","Cabinet","storage","cabinet",800,300,830,None,90,"medium","rect","wood_pine",["storage","utility","solid-pine"],""),
("ikea-besta-shelf-unit-doors","BESTÅ","Shelf unit with door","storage","cabinet",600,420,640,None,120,"medium","rect","white_oak",["living-room","modular","cabinet"],""),
("ikea-trofast-storage-combination","TROFAST","Storage combination with boxes","kids","shelf_unit",990,440,940,None,129,"medium","rect","wood_pine",["kids","toy-storage","modular"],""),
("ikea-skubb-box","SKUBB","Storage box","storage","storage_box",440,550,190,None,10,"medium","rect","white_bb",["storage","wardrobe","fabric"],""),
("ikea-drona-box","DRÖNA","Box","storage","storage_box",330,380,330,None,8,"high","rect","sofa_gray",["storage","kallax-insert","fabric"],""),
("ikea-samla-box","SAMLA","Box with lid, 22 l","storage","storage_box",390,280,140,None,8,"medium","rect","metal_white",["storage","utility","clear"],""),
# ============================================================ LIGHTING
("ikea-nymane-floor-lamp","NYMÅNE","Floor lamp","lighting","floor_lamp",250,250,1550,None,80,"medium","round","metal_dark",["living-room","reading","modern"],""),
("ikea-hektar-floor-lamp","HEKTAR","Floor lamp","lighting","floor_lamp",470,470,1810,None,90,"medium","round","metal_dark",["living-room","industrial","oversized-shade"],""),
("ikea-ranarp-floor-lamp","RANARP","Floor/reading lamp","lighting","floor_lamp",230,230,1500,None,80,"medium","round","metal_black",["living-room","reading","industrial"],""),
("ikea-holmo-floor-lamp","HOLMÖ","Floor lamp","lighting","floor_lamp",250,250,1500,None,25,"medium","round","white",["living-room","paper","budget","ambient"],""),
("ikea-not-floor-uplighter","NOT","Floor uplighter","lighting","floor_lamp",200,200,1750,None,20,"medium","round","metal_black",["living-room","uplighter","budget"],""),
("ikea-lampan-table-lamp","LAMPAN","Table lamp","lighting","table_lamp",190,190,290,None,7,"high","round","white",["bedroom","budget","nightstand"],""),
("ikea-arstid-table-lamp","ÅRSTID","Table lamp","lighting","table_lamp",240,240,550,None,45,"medium","round","metal_white",["living-room","fabric-shade","classic"],""),
("ikea-tertial-work-lamp","TERTIAL","Work lamp","lighting","table_lamp",180,180,550,None,15,"medium","round","metal_dark",["office","task","adjustable"],"Clamp/base work lamp; footprint given for the base version."),
("ikea-fado-table-lamp","FADO","Table lamp","lighting","table_lamp",250,250,220,None,30,"medium","round","white",["bedroom","glass","ambient","orb"],""),
("ikea-ranarp-table-lamp","RANARP","Work lamp","lighting","table_lamp",190,190,420,None,45,"medium","round","metal_black",["office","task","industrial"],""),
("ikea-foto-pendant-380","FOTO","Pendant lamp","lighting","pendant_lamp",380,380,1200,None,35,"high","round","metal_dark",["dining-room","kitchen","dome"],"Shade Ø380; total drop is cord-adjustable, stored as a typical hang."),
("ikea-foto-pendant-500","FOTO","Pendant lamp","lighting","pendant_lamp",500,500,1200,None,50,"medium","round","metal_dark",["dining-room","kitchen","dome","large"],""),
("ikea-hektar-pendant","HEKTAR","Pendant lamp","lighting","pendant_lamp",470,470,1200,None,55,"medium","round","metal_dark",["dining-room","industrial"],""),
("ikea-ranarp-pendant","RANARP","Pendant lamp","lighting","pendant_lamp",380,380,1200,None,60,"medium","round","metal_black",["kitchen","industrial"],""),
("ikea-skurup-pendant","SKURUP","Pendant lamp","lighting","pendant_lamp",380,380,1200,None,40,"medium","round","metal_black",["kitchen","dining-room","cone"],""),
("ikea-nymane-wall-lamp","NYMÅNE","Wall lamp","lighting","wall_lamp",120,220,280,None,35,"low","rect","metal_dark",["bedroom","reading","wall"],"Wall-lamp envelope estimated."),
("ikea-ranarp-wall-lamp","RANARP","Wall/clamp spotlight","lighting","wall_lamp",190,260,230,None,35,"low","rect","metal_black",["bedroom","reading","industrial"],"Envelope estimated."),
("ikea-skurup-wall-lamp","SKURUP","Wall/clamp spotlight","lighting","wall_lamp",130,220,200,None,25,"low","rect","metal_black",["office","task","spotlight"],"Envelope estimated."),
# ============================================================ RUGS
("ikea-stoense-rug-170x240","STOENSE","Rug, low pile","rugs","rug",1700,2400,18,None,199,"high","rect","rug_offwhite",["living-room","low-pile","soft"],""),
("ikea-stoense-rug-200x300","STOENSE","Rug, low pile","rugs","rug",2000,3000,18,None,299,"high","rect","rug_offwhite",["living-room","low-pile","large"],""),
("ikea-vindum-rug-170x230","VINDUM","Rug, high pile","rugs","rug",1700,2300,30,None,199,"medium","rect","rug_gray",["living-room","high-pile","shaggy"],""),
("ikea-hampen-rug-133x195","HAMPEN","Rug, high pile","rugs","rug",1330,1950,38,None,79,"high","rect","rug_gray",["bedroom","high-pile","budget"],""),
("ikea-adum-rug-170x240","ÅDUM","Rug, high pile","rugs","rug",1700,2400,21,None,299,"high","rect","rug_offwhite",["living-room","high-pile","plush"],""),
("ikea-morum-rug-160x230","MORUM","Rug, flatwoven","rugs","rug",1600,2300,8,None,99,"high","rect","rug_natural",["outdoor","flatwoven","indoor-outdoor"],""),
("ikea-morum-rug-200x300","MORUM","Rug, flatwoven","rugs","rug",2000,3000,8,None,179,"medium","rect","rug_natural",["outdoor","flatwoven","large"],""),
("ikea-lohals-rug-160x230","LOHALS","Rug, flatwoven","rugs","rug",1600,2300,13,None,149,"medium","rect","rug_natural",["living-room","jute","natural"],""),
("ikea-tiphede-rug-120x180","TIPHEDE","Rug, flatwoven","rugs","rug",1200,1800,8,None,40,"medium","rect","rug_natural",["kitchen","flatwoven","small"],""),
("ikea-stockholm-rug-170x240","STOCKHOLM","Rug, flatwoven","rugs","rug",1700,2400,10,None,399,"medium","rect","rug_natural",["living-room","wool","premium"],""),
# ============================================================ DECOR
("ikea-lack-wall-shelf-110","LACK","Wall shelf","decor","wall_shelf",1100,260,50,None,25,"high","rect","white_bb",["living-room","floating-shelf","budget"],""),
("ikea-mosslanda-picture-ledge-115","MOSSLANDA","Picture ledge","decor","wall_shelf",1150,120,60,None,15,"medium","rect","white_bb",["living-room","art","ledge"],""),
("ikea-bergshult-wall-shelf-120","BERGSHULT","Wall shelf","decor","wall_shelf",1200,300,25,None,45,"medium","rect","white_bb",["living-room","shelf","modular"],""),
("ikea-ribba-frame-50x70","RIBBA","Frame","decor","art_frame",500,40,700,None,20,"high","rect","white_bb",["art","gallery-wall"],""),
("ikea-bjorksta-picture-140x100","BJÖRKSTA","Picture with frame","decor","art_frame",1400,40,1000,None,169,"medium","rect","metal_black",["art","statement","large"],""),
("ikea-hovsta-frame-61x91","HOVSTA","Frame","decor","art_frame",610,40,910,None,35,"medium","rect","wood_birch",["art","gallery-wall"],""),
("ikea-nissedal-mirror-65","NISSEDAL","Mirror","decor","mirror",650,40,650,None,50,"medium","rect","white_bb",["bedroom","hallway","mirror"],""),
("ikea-hovet-mirror-78x196","HOVET","Mirror","decor","mirror",780,30,1960,None,199,"medium","rect","metal_dark",["bedroom","full-length","mirror"],""),
("ikea-lindbyn-mirror-60","LINDBYN","Mirror","decor","mirror",600,30,600,None,60,"medium","rect","metal_black",["bathroom","hallway","round-mirror"],"Circular mirror: `footprint` is the rect plan bbox because the disc lies in the wall plane, not the floor plane."),
("ikea-fejka-monstera-90","FEJKA","Artificial potted plant, Monstera","decor","plant",400,400,900,None,25,"medium","round","plant",["greenery","artificial","statement"],"Overall height varies with leaf spread; ±80mm."),
("ikea-fejka-plant-45","FEJKA","Artificial potted plant","decor","plant",250,250,450,None,12,"medium","round","plant",["greenery","artificial","tabletop"],""),
("ikea-fejka-ficus-160","FEJKA","Artificial potted plant, Ficus","decor","plant",600,600,1600,None,80,"low","round","plant",["greenery","artificial","floor-plant"],"Tall artificial trees vary widely; low confidence."),
("ikea-lenda-curtains-145x250","LENDA","Curtains with tie-backs, 1 pair","decor","curtain",1450,80,2500,None,40,"high","rect","curtain",["window","cotton","light-filtering"],"Width is per panel; a pair covers ~2900mm of rod."),
("ikea-majgull-curtains-145x250","MAJGULL","Block-out curtains, 1 pair","decor","curtain",1450,90,2500,None,70,"medium","rect","curtain",["window","blackout","bedroom"],""),
("ikea-sanela-curtains-140x250","SANELA","Room darkening curtains, 1 pair","decor","curtain",1400,90,2500,None,80,"medium","rect","curtain",["window","velvet","room-darkening"],""),
# ============================================================ KIDS
("ikea-flisat-childrens-table","FLISAT","Children's table","kids","dining_table_rect",830,580,530,None,89,"medium","rect","wood_pine",["kids","play","solid-pine"],""),
("ikea-mammut-childrens-chair","MAMMUT","Children's chair","kids","dining_chair",390,360,530,300,15,"medium","rect","white_bb",["kids","plastic","indoor-outdoor"],""),
("ikea-sundvik-childrens-table","SUNDVIK","Children's table","kids","dining_table_rect",760,500,500,None,79,"low","rect","white_bb",["kids","play"],"Estimated."),
("ikea-kritter-childrens-chair","KRITTER","Children's chair","kids","dining_chair",290,340,570,310,20,"low","rect","white_bb",["kids","solid-wood"],"Estimated."),
# ============================================================ TV (non-IKEA, generic screens for layout math)
("generic-tv-55","Generic","55-inch flat-panel TV","decor","tv",1230,60,710,None,499,"high","rect","tv",["living-room","screen","55in"],"Industry-standard 55\" 16:9 panel envelope (1228x709mm active + bezel)."),
("generic-tv-65","Generic","65-inch flat-panel TV","decor","tv",1450,65,830,None,799,"high","rect","tv",["living-room","screen","65in"],"Industry-standard 65\" 16:9 panel envelope."),
("generic-tv-43","Generic","43-inch flat-panel TV","decor","tv",960,55,560,None,299,"high","rect","tv",["bedroom","screen","43in"],"Industry-standard 43\" 16:9 panel envelope."),
]
